name: CI

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: Test
      working-directory: <path to repo>
      shell: cmd
      run: ${{ secrets.PULL }}
